export const carData = {
    "Acura": ["MDX", "RDX", "TLX", "Integra", "ZDX"],
    "Audi": ["A3", "A4", "A5", "A6", "Q3", "Q5", "Q7", "Q8", "e-tron"],
    "BMW": ["3 Series", "4 Series", "5 Series", "X1", "X3", "X5", "X7", "i4", "iX"],
    "Chevrolet": ["Silverado 1500", "Equinox", "Trax", "Tahoe", "Colorado", "Corvette", "Blazer", "Trailblazer"],
    "Chrysler": ["Pacifica", "300"],
    "Dodge": ["Charger", "Challenger", "Durango", "Hornet"],
    "Ford": ["F-150", "Escape", "Explorer", "Bronco", "Bronco Sport", "Mustang", "Mustang Mach-E", "Edge", "Ranger"],
    "Genesis": ["G70", "G80", "GV70", "GV80"],
    "GMC": ["Sierra 1500", "Terrain", "Acadia", "Yukon", "Canyon"],
    "Honda": ["CR-V", "Civic", "Accord", "Pilot", "HR-V", "Odyssey", "Ridgeline"],
    "Hyundai": ["Tucson", "Elantra", "Santa Fe", "Palisade", "Kona", "Sonata", "Ioniq 5", "Ioniq 6"],
    "Jeep": ["Grand Cherokee", "Wrangler", "Compass", "Gladiator", "Wagoneer"],
    "Kia": ["Sportage", "Forte", "Telluride", "Sorento", "Soul", "EV6", "EV9"],
    "Lexus": ["RX", "NX", "ES", "IS", "GX", "TX"],
    "Mazda": ["CX-5", "CX-30", "CX-50", "CX-90", "Mazda3"],
    "Mercedes-Benz": ["C-Class", "E-Class", "GLC", "GLE", "GLS", "EQE", "EQS"],
    "Nissan": ["Rogue", "Sentra", "Altima", "Pathfinder", "Frontier", "Kicks"],
    "Porsche": ["Macan", "Cayenne", "911", "Panamera", "Taycan"],
    "Ram": ["1500", "2500", "3500"],
    "Subaru": ["Outback", "Crosstrek", "Forester", "Ascent", "Impreza"],
    "Tesla": ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
    "Toyota": ["RAV4", "Camry", "Corolla", "Highlander", "Tacoma", "Tundra", "4Runner", "Sienna", "Prius", "Grand Highlander"],
    "Volkswagen": ["Tiguan", "Taos", "Atlas", "Jetta", "Golf GTI", "ID.4"],
    "Volvo": ["XC90", "XC60", "XC40", "S60", "V60"]
};
